name: craft_dynamic
version: 0.0.1
publish_to: https://onepub.dev/api/fvluhnofly/
description: A new Flutter package project.
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  archive: ^3.3.2
  cached_network_image: ^3.2.3
  camera: ^0.10.0+4
  date_format: ^2.0.7
  dio: ^5.1.1
  dropdown_button2: ^1.9.1
  encrypt: ^5.0.1
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: any
  fluttercontactpicker: ^4.7.0
  group_button: ^5.2.2
  hex: ^0.2.0
  image_picker: ^0.8.6
  intl: any
  local_auth: ^2.1.2
  local_auth_android: ^1.0.32
  local_auth_ios: ^1.1.3
  crypto: ^3.0.3
  logger: ^1.1.0
  lottie: ^2.0.0
  package_info_plus: ^4.0.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  unique_identifier: ^0.2.0
  url_launcher: ^6.1.7
  uuid: ^3.0.6
  vibration: ^1.7.6
  local_session_timeout: ^2.1.1
  get: ^4.6.5
  fluttertoast: any
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  yaml: ^3.1.1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.0
  flutter_spinkit: ^5.1.0
  rsa_encrypt: ^2.0.0
  asn1lib: ^1.4.0
  pointycastle: ^3.6.2
  pem: ^2.0.2
  convert: ^3.1.1
  easy_localization: ^3.0.1
  connectivity_plus: 3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # platform_device_id: ^1.0.1
  flutter_multi_formatter: ^2.11.0
  blur: ^3.1.0
  logging: ^1.2.0
  syncfusion_flutter_pdf: ^27.1.56
  share_plus: ^7.0.2
  open_file: ^3.3.1
  qr_code_scanner: 1.0.1
  intl_phone_number_input: ^0.7.3+1
  collection: any
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  pinput: ^3.0.1
  pdf_render: ^1.4.0
  flutter_libphonenumber: ^2.2.2
  # libphonenumber: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - packages/craft_dynamic/assets/lottie/loading.json
    - packages/craft_dynamic/assets/lottie/loading_list.json
    - packages/craft_dynamic/assets/lottie/error.json
    - packages/craft_dynamic/assets/lottie/success.json
    - packages/craft_dynamic/assets/lottie/information.json
    - packages/craft_dynamic/assets/images/fingerprint.png
    - packages/craft_dynamic/assets/images/qr-code.png
    - packages/craft_dynamic/assets/lottie/info_lottie.json
    - packages/craft_dynamic/assets/images/warning.png
    - packages/craft_dynamic/assets/images/empty.png
